export const settings = {
  APP_NAME: 'Foams',
  APPLE_APP_ID: '1466460494',
  APPLE_APP_URL: 'https://apps.apple.com/us/app/foams-app/id1466460494',
  ANDROID_APP_ID: 'com.wavelinkllc.foamsapp',
  ANDROID_APP_URL: 'http://play.google.com/store/apps/details?id=com.wavelinkllc.foamsapp',
  APP_VERSION: '2.1',
  WEBSITE_URL: 'http://linkable.bio/foamlicious',
  PRIVACY_POLICY_URL: 'http://wavelinkllc.com/foamlicious/privacypolicy/',
  DISCLAIMER_MESSAGE: '\'Foams\' and it\'s creator are not affiliated with the \'Nike\' or \'Nike Foamposite\' brands.',
  EMAIL_ADDRESS: 'foamlicious1@gmail.com',
  TWITTER_HANDLE: 'foamlicious',
  INSTAGRAM_HANDLE: 'foams.app',
  FACEBOOK_ID: '380411992097769',
  FACEBOOK_NAME: 'Foamlicious',
  SNAPCHAT_NAME: 'Foams',
};